import Link from "next/link";

import { listInterviewTranscripts } from "@/lib/interview/transcript-query";

export const dynamic = "force-dynamic";

function formatTimestamp(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

export default async function TranscriptsPage() {
  const transcripts = await listInterviewTranscripts();

  return (
    <main className="transcript-browser-shell">
      <section className="transcript-browser-card">
        <header className="transcript-browser-header">
          <div>
            <p className="eyebrow">Developer view</p>
            <h1>Interview transcripts</h1>
            <p className="lede">
              Browse locally saved transcript files generated by the interview
              flow.
            </p>
          </div>
          <div className="browser-actions">
            <Link className="secondary-button" href="/">
              Back to home
            </Link>
          </div>
        </header>

        {transcripts.length === 0 ? (
          <div className="transcript-empty-panel">
            <strong>No transcripts saved yet.</strong>
            <p>
              Complete at least one interview to generate a JSON transcript
              under <code>data/interviews/</code>.
            </p>
          </div>
        ) : (
          <div className="transcript-table">
            {transcripts.map((transcript) => (
              <article className="transcript-list-card" key={transcript.interviewId}>
                <div className="transcript-list-top">
                  <div>
                    <p className="eyebrow">Candidate</p>
                    <h2>{transcript.candidateName}</h2>
                    <p className="supporting-copy">{transcript.roleTitle}</p>
                  </div>
                  <span className={`connection-pill ${transcript.status}`}>
                    {transcript.status}
                  </span>
                </div>

                <dl className="transcript-meta-grid">
                  <div>
                    <dt>Interview ID</dt>
                    <dd>{transcript.interviewId}</dd>
                  </div>
                  <div>
                    <dt>Token</dt>
                    <dd>{transcript.token}</dd>
                  </div>
                  <div>
                    <dt>Saved</dt>
                    <dd>{formatTimestamp(transcript.savedAt)}</dd>
                  </div>
                  <div>
                    <dt>Entries</dt>
                    <dd>{transcript.entryCount}</dd>
                  </div>
                </dl>

                <p className="transcript-preview-copy">
                  {transcript.lastUtterance ?? "No final transcript entries yet."}
                </p>

                <div className="browser-actions">
                  <Link
                    className="primary-link"
                    href={`/transcripts/${transcript.interviewId}`}
                  >
                    Open transcript
                  </Link>
                </div>
              </article>
            ))}
          </div>
        )}
      </section>
    </main>
  );
}
